### ISSUE TITLE
OAuth grant_type=client_credentials

### ISSUE THREAD

**Issue by leojhartiv** [niranjan94/rest-data-connector#1]
Does this support OAuth grant_type=client_credentials?  My REST api requires me to access it this way:
![image](https://user-images.githubusercontent.com/141352/53981905-9b5ea080-40e1-11e9-872f-66b92d65b9f2.png)

https://aaronparecki.com/oauth-2-simplified/#client-credentials

I tried this in the connector:
![image](https://user-images.githubusercontent.com/141352/53982090-03ad8200-40e2-11e9-93b8-3cf0eee96c8f.png)

It didn't give me an error message, but didn't seem to do anything either.  

Thanks!

**Comment by niranjan94** [comment]
@leojhartiv the authentication with `client_credentials` should be done outside of the connector and only the authtoken should be used here. 

To be clear,

```
POST https://api.authorization-server.com/token
    grant_type=client_credentials&
    client_id=CLIENT_ID&
    client_secret=CLIENT_SECRET
```

Should be done outside using a tool like Postman or curl. 

And token you get from that can be put in the token field of the REST data connector.
